"""Generate the 1-day campaign: pick held-out + nested breadth subsets from the
cached MDR pool, then emit scripts/campaign_materials.sh (bash vars) and
scripts/jobs.tsv (all experiment groups). Run on the machine holding the cache.

Design:
  HOLD     = original 6 transfer materials + 4 extra (fixed, never trained on)
  B16      = the original 16-material TRAIN set (connects to prior results)
  B4 c B8 c B16 c B32 c B64   nested, greedy max-element-coverage ordering
Groups written to jobs.tsv (cols: JOB SEED NCFG MODE MODEL TRAINKEY):
  G1 breadth headline   N in {B4,B8,B16,B32,B64} x seed{1,2,3}, pt1000, 30cfg
  G2 seed error bars    {single,pt1000,pt5000,lora8,lora32} x seed{2,3,4} on B16
  G3 replay x breadth   B32 x {single,pt500,pt1000,pt2500} x seed{1,2}
  G4 depth x breadth    {B16,B32,B64} x ncfg{15,60} x seed1, pt1000
  G5 bigger foundation  {B8,B16,B32,B64} x seed1, pt1000, model=medium
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from phonon_accel import reference  # noqa: E402

CACHE = ROOT / "data" / "benchmark" / "mdr"
idx = reference._index()
cached = sorted(p.name.split("_")[0] for p in CACHE.glob("*_phonopy_params.yaml"))


def elems(mp):
    f = idx.get(mp, {}).get("formula", "")
    return set(re.findall(r"[A-Z][a-z]?", f))


# --- original splits (continuity with prior results) ---
ORIG_TRAIN = "mp-149 mp-1265 mp-22862 mp-661 mp-9946 mp-804 mp-2172 mp-1986 mp-23193 mp-2741 mp-2472 mp-406 mp-4651 mp-1143 mp-2490 mp-1960".split()
ORIG_HOLD = "mp-7140 mp-984 mp-1138 mp-2605 mp-20351 mp-390".split()

pool = [m for m in cached if m not in ORIG_TRAIN and m not in ORIG_HOLD]

# --- HOLD = the original 6 transfer materials (proven good: SiC, BN, LiF, ...).
# NB: do NOT auto-add "short-formula common-element" materials -- that heuristic
# picks pathological molecular/elemental crystals (P allotrope, F2, KP) with huge
# soft cells (1000s of spurious imaginary modes + minutes-long eval). 6 fixed,
# all-fast holdout materials is a clean transfer set. ---
HOLD = ORIG_HOLD
pool = [m for m in pool if m not in HOLD]


def greedy_cover(seed_list, candidates, target):
    """Extend seed_list with candidates, greedily maximizing new-element coverage."""
    chosen = list(seed_list)
    seen = set().union(*(elems(m) for m in chosen)) if chosen else set()
    cand = list(candidates)
    while len(chosen) < target and cand:
        cand.sort(key=lambda m: (-len(elems(m) - seen), len(idx[m]["formula"])))
        m = cand.pop(0)
        chosen.append(m)
        seen |= elems(m)
    return chosen


# B16 = original 16, internally ordered for greedy coverage so B4/B8 are diverse
b16 = greedy_cover([], ORIG_TRAIN, 16)
B4, B8, B16 = b16[:4], b16[:8], b16
B32 = greedy_cover(B16, pool, 32)
B64 = greedy_cover(B32, [m for m in pool if m not in B32], 64)

sets = {"B4": B4, "B8": B8, "B16": B16, "B32": B32, "B64": B64, "TRAIN16": ORIG_TRAIN}
for k in ["B4", "B8", "B16", "B32", "B64"]:
    print(f"{k}: {len(sets[k])} materials, {len(set().union(*(elems(m) for m in sets[k])))} elements")
print(f"HOLD: {len(HOLD)} materials -> {sorted(set().union(*(elems(m) for m in HOLD)))}")

# --- emit campaign_materials.sh ---
mats = ROOT / "scripts" / "campaign_materials.sh"
with open(mats, "w") as f:
    f.write("#!/usr/bin/env bash\n# AUTO-GENERATED by gen_campaign.py\n")
    f.write(f'HOLD="{" ".join(HOLD)}"\n')
    for k in ["B4", "B8", "B16", "B32", "B64", "TRAIN16"]:
        f.write(f'{k}="{" ".join(sets[k])}"\n')
print("wrote", mats)

# --- emit jobs.tsv ---
jobs = []  # (JOB, SEED, NCFG, MODE, MODEL, TRAINKEY)
# G1 breadth headline
for key in ["B4", "B8", "B16", "B32", "B64"]:
    for s in (1, 2, 3):
        jobs.append((f"br_{key}_s{s}", s, 30, "pt1000", "small", key))
# G2 seed error bars on B16
for mode in ["single", "pt1000", "pt5000", "lora8", "lora32"]:
    for s in (2, 3, 4):
        jobs.append((f"eb_{mode}_s{s}", s, 30, mode, "small", "B16"))
# G3 replay x breadth at B32
for mode in ["single", "pt500", "pt1000", "pt2500"]:
    for s in (1, 2):
        jobs.append((f"rb_{mode}_s{s}", s, 30, mode, "small", "B32"))
# G4 depth x breadth
for key in ["B16", "B32", "B64"]:
    for nc in (15, 60):
        jobs.append((f"db_{key}_nc{nc}", 1, nc, "pt1000", "small", key))
# G5 bigger foundation model (medium) breadth
for key in ["B8", "B16", "B32", "B64"]:
    jobs.append((f"med_{key}", 1, 30, "pt1000", "medium", key))

# interleave so heavy (large N / medium model) jobs spread across the round-robin
order = sorted(range(len(jobs)), key=lambda i: (jobs[i][5], jobs[i][4]))  # not strictly needed
out = ROOT / "scripts" / "jobs.tsv"
with open(out, "w") as f:
    f.write("#JOB\tSEED\tNCFG\tMODE\tMODEL\tTRAINKEY\n")
    for j in jobs:
        f.write("\t".join(str(x) for x in j) + "\n")
print(f"wrote {out}: {len(jobs)} jobs")
