#!/usr/bin/env python3
"""Diagnose the matrix rank of the graphene EPW correction at the K star.

This development check uses the existing 300/450/600 K q6 Cartesian
operators.  It asks whether the electronic correction and its smearing
dependence require more than the tracked A' phonon subspace.  No DFT data are
generated by this script.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parents[2]
TEMPERATURES = (300, 450, 600)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_json(path: Path, payload: dict) -> None:
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def hermitian(matrix: np.ndarray) -> np.ndarray:
    return (matrix + matrix.conj().T) / 2.0


def rank_capture(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    values, vectors = np.linalg.eigh(hermitian(matrix))
    order = np.argsort(np.abs(values))[::-1]
    values = values[order]
    vectors = vectors[:, order]
    weights = np.abs(values) ** 2
    capture = np.cumsum(weights) / np.sum(weights)
    return values, vectors, capture


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=(
            ROOT
            / "results/graphene_physics_temperature/post_p4_feasibility"
            / "E0_epw_matched/k18_q9_ex1_pifroz/operator_q6_450K"
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=(
            ROOT
            / "results/graphene_physics_temperature/post_p4_feasibility"
            / "E3_epw_kstar_low_rank"
        ),
    )
    args = parser.parse_args()

    matrix_path = args.input_dir / "matdyn/epw_q6_dynamical_matrices.npz"
    with np.load(matrix_path, allow_pickle=False) as payload:
        qpoints = np.asarray(payload["qpoints_crystal"], float)
        bare = np.asarray(payload["dynamical_matrices"], complex)
        scale = float(payload["dynamical_matrix_scale_cm2"])

    operator_paths = {
        temperature: args.input_dir / f"cartesian/T{temperature}_operator.npz"
        for temperature in TEMPERATURES
    }
    operators = {}
    smearings = {}
    for temperature, path in operator_paths.items():
        with np.load(path, allow_pickle=False) as payload:
            if not np.allclose(payload["qpoints_crystal"], qpoints, atol=1.0e-12):
                raise ValueError(f"q-point mismatch in {path}")
            operators[temperature] = np.asarray(payload["delta_dynamical_q"], complex)
            smearings[temperature] = float(payload["degauss_Ry"])

    target_k = (np.asarray([1.0 / 3.0, 1.0 / 3.0, 0.0]),
                np.asarray([2.0 / 3.0, 2.0 / 3.0, 0.0]))
    k_indices = []
    for target in target_k:
        periodic = qpoints - target
        periodic -= np.rint(periodic)
        index = int(np.argmin(np.linalg.norm(periodic, axis=1)))
        if np.linalg.norm(periodic[index]) > 1.0e-9:
            raise ValueError(f"K-star point {target} is absent from the q6 grid")
        k_indices.append(index)

    records = []
    lead_vectors: dict[tuple[int, int], np.ndarray] = {}
    for star_index, q_index in enumerate(k_indices):
        _, bare_vectors = np.linalg.eigh(hermitian(bare[q_index]))
        for temperature in TEMPERATURES:
            correction = hermitian(operators[temperature][q_index])
            values, vectors, capture = rank_capture(correction)
            lead_vectors[(star_index, temperature)] = vectors[:, 0]
            in_bare_basis = bare_vectors.conj().T @ correction @ bare_vectors
            diagonal = np.diag(np.diag(in_bare_basis))
            norm_squared = float(np.linalg.norm(in_bare_basis) ** 2)
            records.append(
                {
                    "K_star_index": star_index,
                    "qpoint_crystal": qpoints[q_index].tolist(),
                    "temperature_K": temperature,
                    "degauss_Ry": smearings[temperature],
                    "eigenvalues_by_abs_cm-2": (values * scale).real.tolist(),
                    "rank1_frobenius_capture": float(capture[0]),
                    "rank2_frobenius_capture": float(capture[1]),
                    "bare_mode_diagonal_fraction": float(
                        np.linalg.norm(diagonal) ** 2 / norm_squared
                    ),
                    "A_prime_top_mode_fraction": float(
                        abs(in_bare_basis[-1, -1]) ** 2 / norm_squared
                    ),
                    "A_prime_delta_lambda_cm-2": float(
                        in_bare_basis[-1, -1].real * scale
                    ),
                }
            )

    overlaps = []
    difference_records = []
    for star_index, q_index in enumerate(k_indices):
        for left, right in ((300, 450), (450, 600), (300, 600)):
            overlap = float(
                abs(
                    np.vdot(
                        lead_vectors[(star_index, left)],
                        lead_vectors[(star_index, right)],
                    )
                )
                ** 2
            )
            overlaps.append(
                {
                    "K_star_index": star_index,
                    "temperatures_K": [left, right],
                    "leading_projector_overlap": overlap,
                }
            )
            difference = hermitian(
                operators[left][q_index] - operators[right][q_index]
            )
            values, _, capture = rank_capture(difference)
            difference_records.append(
                {
                    "K_star_index": star_index,
                    "temperatures_K": [left, right],
                    "eigenvalues_by_abs_cm-2": (values * scale).real.tolist(),
                    "rank1_frobenius_capture": float(capture[0]),
                    "rank2_frobenius_capture": float(capture[1]),
                }
            )

    aggregate = {
        "minimum_operator_rank1_capture": min(
            row["rank1_frobenius_capture"] for row in records
        ),
        "minimum_A_prime_top_mode_fraction": min(
            row["A_prime_top_mode_fraction"] for row in records
        ),
        "minimum_bare_mode_diagonal_fraction": min(
            row["bare_mode_diagonal_fraction"] for row in records
        ),
        "minimum_cross_smearing_projector_overlap": min(
            row["leading_projector_overlap"] for row in overlaps
        ),
        "minimum_temperature_difference_rank1_capture": min(
            row["rank1_frobenius_capture"] for row in difference_records
        ),
    }
    checks = {
        "operator_rank1_capture_ge_0p995": (
            aggregate["minimum_operator_rank1_capture"] >= 0.995
        ),
        "A_prime_top_mode_fraction_ge_0p99": (
            aggregate["minimum_A_prime_top_mode_fraction"] >= 0.99
        ),
        "bare_mode_diagonal_fraction_ge_0p999": (
            aggregate["minimum_bare_mode_diagonal_fraction"] >= 0.999
        ),
        "cross_smearing_projector_overlap_ge_0p99": (
            aggregate["minimum_cross_smearing_projector_overlap"] >= 0.99
        ),
        "temperature_difference_rank1_capture_ge_0p995": (
            aggregate["minimum_temperature_difference_rank1_capture"] >= 0.995
        ),
    }
    status = "rank_one_A_prime_supported" if all(checks.values()) else "rank_one_not_supported"

    args.output_dir.mkdir(parents=True, exist_ok=True)
    summary = {
        "status": status,
        "scope": "existing q6 EPW Cartesian operators at the graphene K star; no new DFT",
        "interpretation": (
            "retain a tracked Hermitian rank-one A-prime projector and improve its "
            "q/smearing scalar self-energy"
            if all(checks.values())
            else "test a larger anomalous-mode subspace before fitting a scalar kernel"
        ),
        "aggregate": aggregate,
        "checks": checks,
        "operators_at_K_star": records,
        "cross_smearing_projector_overlaps": overlaps,
        "temperature_differences": difference_records,
        "inputs": {
            "bare_matrices": {"path": str(matrix_path), "sha256": sha256(matrix_path)},
            "operators": {
                str(temperature): {"path": str(path), "sha256": sha256(path)}
                for temperature, path in operator_paths.items()
            },
        },
        "limitations": [
            "The q6 grid establishes the anomalous matrix subspace but is too coarse to resolve the cusp width.",
            "The dense-q scalar law must be validated separately against the existing K-line data.",
        ],
    }
    atomic_json(args.output_dir / "epw_kstar_low_rank_summary.json", summary)

    fig, axis = plt.subplots(figsize=(6.8, 3.8))
    x = np.arange(6)
    width = 0.23
    selected_star = 0
    for offset, temperature in enumerate(TEMPERATURES):
        row = next(
            item
            for item in records
            if item["K_star_index"] == selected_star
            and item["temperature_K"] == temperature
        )
        values = np.abs(np.asarray(row["eigenvalues_by_abs_cm-2"], float))
        axis.bar(
            x + (offset - 1) * width,
            values,
            width,
            label=f"degauss = {row['degauss_Ry']:.7f} Ry",
        )
    axis.set_yscale("log")
    axis.set_xticks(x, [f"{index}" for index in range(1, 7)])
    axis.set_xlabel("correction eigenchannel, ordered by magnitude")
    axis.set_ylabel(r"$|\Delta\lambda|$ (cm$^{-2}$)")
    axis.set_title("EPW correction at K is dominated by one A′ channel")
    axis.grid(axis="y", color="#E6E6E6", lw=0.55)
    axis.spines[["top", "right"]].set_visible(False)
    axis.legend(loc="upper left", bbox_to_anchor=(1.02, 1.0), frameon=False)
    fig.subplots_adjust(left=0.12, right=0.70, top=0.88, bottom=0.18)
    fig.savefig(
        args.output_dir / "epw_kstar_eigenchannels.png",
        dpi=220,
        facecolor="white",
        bbox_inches="tight",
    )
    plt.close(fig)
    print(json.dumps(summary, indent=2))
    return 0 if all(checks.values()) else 2


if __name__ == "__main__":
    raise SystemExit(main())
