#!/usr/bin/env python3
"""Audit atom-local support and conservative radial residuals for graphene R2D.

This diagnostic uses only geometry to define local support against the
corrected-X0 ensemble.  DFT force residuals are read only after those support
scores have been constructed.  It then decomposes candidate force errors into
the subspace generated by central forces on first-neighbour C--C bonds and the
orthogonal remainder, including their folded-K A-prime projections.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from ase.io import read
from mace.calculators import MACECalculator
from scipy.spatial import cKDTree
from scipy.stats import spearmanr


ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from audit_graphene_current_s0_fixed_smearing import (  # noqa: E402
    complex_metrics,
    folded_k_aprime_mode,
    force_metrics,
    load_operator,
    structure_mapping,
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def atomic_csv(path: Path, fieldnames: list[str], rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    os.replace(temporary, path)


def atomic_npz(path: Path, **arrays) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("wb") as handle:
        np.savez(handle, **arrays)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


def minimum_image_vectors(positions: np.ndarray, cell: np.ndarray) -> np.ndarray:
    """Return vectors from atom i to atom j under the minimum-image convention."""
    delta = positions[None, :, :] - positions[:, None, :]
    fractional = delta @ np.linalg.inv(cell)
    fractional -= np.round(fractional)
    return fractional @ cell


def local_features(
    positions: np.ndarray, cell: np.ndarray, n_distances: int = 12
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Rotation/permutation-invariant local distance and first-shell angle features."""
    vectors = minimum_image_vectors(np.asarray(positions, float), cell)
    distances = np.linalg.norm(vectors, axis=2)
    np.fill_diagonal(distances, np.inf)
    order = np.argsort(distances, axis=1)
    nearest = np.take_along_axis(distances, order[:, :n_distances], axis=1)
    first_three_indices = order[:, :3]
    first_three_vectors = np.take_along_axis(
        vectors, first_three_indices[:, :, None], axis=1
    )
    first_three_lengths = np.linalg.norm(first_three_vectors, axis=2)
    unit = first_three_vectors / first_three_lengths[:, :, None]
    cosine = np.stack(
        [
            np.sum(unit[:, 0] * unit[:, 1], axis=1),
            np.sum(unit[:, 0] * unit[:, 2], axis=1),
            np.sum(unit[:, 1] * unit[:, 2], axis=1),
        ],
        axis=1,
    )
    cosine.sort(axis=1)
    return np.concatenate([nearest, cosine], axis=1), distances, vectors


def robust_scale(reference: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    center = np.median(reference, axis=0)
    lower, upper = np.quantile(reference, [0.25, 0.75], axis=0)
    scale = (upper - lower) / 1.349
    standard = np.std(reference, axis=0)
    scale = np.where(scale > 1.0e-8, scale, standard)
    scale = np.where(scale > 1.0e-8, scale, 1.0)
    return center, scale


def reference_cross_configuration_knn(
    scaled: np.ndarray, config_index: np.ndarray, neighbours: int = 5
) -> tuple[np.ndarray, cKDTree]:
    """Mean kNN distance excluding atoms from the query's own configuration."""
    tree = cKDTree(scaled)
    query_k = min(160, len(scaled))
    distance, index = tree.query(scaled, k=query_k, workers=-1)
    score = np.empty(len(scaled), float)
    for row in range(len(scaled)):
        allowed = distance[row][config_index[index[row]] != config_index[row]]
        if len(allowed) < neighbours:
            raise RuntimeError("not enough cross-configuration local neighbours")
        score[row] = float(np.mean(allowed[:neighbours]))
    return score, tree


def percentile_against_reference(values: np.ndarray, reference: np.ndarray) -> np.ndarray:
    ordered = np.sort(np.asarray(reference, float))
    return (
        np.searchsorted(ordered, np.asarray(values, float), side="right")
        / len(ordered)
        * 100.0
    )


def central_pair_projection(
    error: np.ndarray,
    distances: np.ndarray,
    vectors: np.ndarray,
    neighbour_cutoff_A: float,
) -> dict:
    atom_i, atom_j = np.where(
        np.triu((distances < neighbour_cutoff_A), k=1)
    )
    if len(atom_i) == 0:
        raise ValueError("no first-neighbour bonds found")
    matrix = np.zeros((error.size, len(atom_i)), float)
    for column, (left, right) in enumerate(zip(atom_i, atom_j, strict=True)):
        unit = vectors[left, right] / distances[left, right]
        matrix[3 * left : 3 * left + 3, column] = unit
        matrix[3 * right : 3 * right + 3, column] = -unit
    flat = np.asarray(error, float).reshape(-1)
    coefficients, *_ = np.linalg.lstsq(matrix, flat, rcond=1.0e-10)
    projected = matrix @ coefficients
    remainder = flat - projected
    norm2 = float(np.vdot(flat, flat).real)

    shortest_column = int(np.argmin(distances[atom_i, atom_j]))
    shortest_mode = matrix[:, shortest_column]
    shortest_mode /= np.linalg.norm(shortest_mode)
    shortest_amplitude = float(np.vdot(shortest_mode, flat).real)
    shortest_projection = shortest_amplitude * shortest_mode
    return {
        "projected": projected.reshape(error.shape),
        "remainder": remainder.reshape(error.shape),
        "radial_explained_fraction": (
            float(np.vdot(projected, projected).real / norm2) if norm2 > 0 else 0.0
        ),
        "shortest_bond_explained_fraction": (
            float(np.vdot(shortest_projection, shortest_projection).real / norm2)
            if norm2 > 0
            else 0.0
        ),
        "n_first_neighbour_bonds": int(len(atom_i)),
        "shortest_pair": [int(atom_i[shortest_column]), int(atom_j[shortest_column])],
        "shortest_distance_A": float(
            distances[atom_i[shortest_column], atom_j[shortest_column]]
        ),
        "shortest_stretch_error_amplitude_meV_A": shortest_amplitude * 1000.0,
    }


def quantiles(values: np.ndarray) -> dict[str, float]:
    levels = [0.0, 0.01, 0.05, 0.5, 0.95, 0.99, 1.0]
    result = np.quantile(np.asarray(values, float), levels)
    return {f"q{int(level * 100):02d}": float(value) for level, value in zip(levels, result)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ensemble-xats", type=Path, required=True)
    parser.add_argument("--support-data", type=Path, required=True)
    parser.add_argument("--candidate-model", type=Path, required=True)
    parser.add_argument("--operator", type=Path, required=True)
    parser.add_argument("--background", type=Path, required=True)
    parser.add_argument("--corrected-result", type=Path, required=True)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--local-ood-percentile", type=float, default=99.0)
    parser.add_argument("--neighbour-cutoff-A", type=float, default=1.75)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    support = read(args.support_data, index=":")
    if len(support) != 9:
        raise ValueError("support development data must contain nine structures")
    xats = np.load(args.ensemble_xats)
    if xats.ndim != 3 or xats.shape[1:] != (len(support[0]), 3):
        raise ValueError(f"unexpected corrected-X0 xats shape: {xats.shape}")

    _, reference, cell, degauss = load_operator(args.operator)
    for structure in support:
        if not np.allclose(np.asarray(structure.cell), cell, atol=2.0e-5, rtol=0.0):
            raise ValueError("support and operator cells differ")
    mode, mode_provenance = folded_k_aprime_mode(
        args.background, args.corrected_result, reference, cell
    )

    reference_features = []
    reference_config_index = []
    reference_atom_index = []
    reference_minimum_bond = []
    for config, positions in enumerate(xats):
        features, distances, _ = local_features(positions, cell)
        reference_features.append(features)
        reference_config_index.extend([config] * len(positions))
        reference_atom_index.extend(range(len(positions)))
        reference_minimum_bond.append(float(np.min(distances)))
    reference_features = np.concatenate(reference_features, axis=0)
    reference_config_index = np.asarray(reference_config_index, int)
    reference_atom_index = np.asarray(reference_atom_index, int)
    reference_minimum_bond = np.asarray(reference_minimum_bond, float)

    center, scale = robust_scale(reference_features)
    reference_scaled = (reference_features - center) / scale
    reference_knn, tree = reference_cross_configuration_knn(
        reference_scaled, reference_config_index
    )

    support_features = []
    support_distances = []
    support_vectors = []
    for structure in support:
        features, distances, vectors = local_features(structure.positions, cell)
        support_features.append(features)
        support_distances.append(distances)
        support_vectors.append(vectors)
    support_features_array = np.concatenate(support_features, axis=0)
    support_scaled = (support_features_array - center) / scale
    support_knn_distance, support_knn_index = tree.query(
        support_scaled, k=5, workers=-1
    )
    support_knn = np.mean(support_knn_distance, axis=1)
    support_percentile = percentile_against_reference(support_knn, reference_knn)
    support_knn = support_knn.reshape(len(support), len(support[0]))
    support_percentile = support_percentile.reshape(len(support), len(support[0]))
    support_knn_index = support_knn_index.reshape(len(support), len(support[0]), 5)

    calculator = MACECalculator(
        model_paths=str(args.candidate_model),
        device=args.device,
        default_dtype="float32",
    )
    errors = []
    predictions = []
    for source in support:
        structure = source.copy()
        structure.calc = calculator
        prediction = np.asarray(structure.get_forces(), float)
        predictions.append(prediction)
        errors.append(prediction - np.asarray(source.arrays["SHORT_RANGE_TARGET_forces"], float))
    errors = np.asarray(errors)
    predictions = np.asarray(predictions)

    config_rows = []
    atom_rows = []
    projected_errors = []
    remainder_errors = []
    aprime_errors = []
    aprime_radial_errors = []
    aprime_remainder_errors = []
    for config, structure in enumerate(support):
        index = int(structure.info["sscha_index"])
        decomposition = central_pair_projection(
            errors[config],
            support_distances[config],
            support_vectors[config],
            args.neighbour_cutoff_A,
        )
        projected = decomposition.pop("projected")
        remainder = decomposition.pop("remainder")
        projected_errors.append(projected)
        remainder_errors.append(remainder)

        mapping, _ = structure_mapping(structure, reference, cell)
        structure_mode = mode[mapping]
        mode_flat = structure_mode.reshape(-1)
        aprime = np.vdot(mode_flat, errors[config].reshape(-1))
        aprime_radial = np.vdot(mode_flat, projected.reshape(-1))
        aprime_remainder = np.vdot(mode_flat, remainder.reshape(-1))
        aprime_errors.append(aprime)
        aprime_radial_errors.append(aprime_radial)
        aprime_remainder_errors.append(aprime_remainder)

        minimum_bond = float(np.min(support_distances[config]))
        lower_tail = float(np.mean(reference_minimum_bond <= minimum_bond) * 100.0)
        atom_error = np.linalg.norm(errors[config], axis=1) * 1000.0
        max_atom = int(np.argmax(atom_error))
        row = {
            "sscha_index": index,
            "support_level": str(structure.info["corrected_X0_support_level"]),
            "minimum_bond_A": minimum_bond,
            "minimum_bond_corrected_X0_lower_tail_percentile": lower_tail,
            "maximum_atom_local_knn_percentile": float(np.max(support_percentile[config])),
            "n_atoms_above_local_ood_percentile": int(
                np.sum(support_percentile[config] >= args.local_ood_percentile)
            ),
            "force_RMSE_meV_A": force_metrics(errors[config][None])["RMSE_meV_A"],
            "force_max_abs_meV_A": force_metrics(errors[config][None])["max_abs_meV_A"],
            "maximum_vector_error_atom": max_atom,
            "maximum_atom_force_error_norm_meV_A": float(atom_error[max_atom]),
            "Aprime_force_error_abs_meV_A": float(abs(aprime) * 1000.0),
            "Aprime_radial_part_abs_meV_A": float(abs(aprime_radial) * 1000.0),
            "Aprime_remainder_part_abs_meV_A": float(abs(aprime_remainder) * 1000.0),
            **decomposition,
        }
        config_rows.append(row)

        for atom in range(len(structure)):
            neighbours = support_knn_index[config, atom]
            atom_rows.append(
                {
                    "sscha_index": index,
                    "atom_index": atom,
                    "local_knn_score": float(support_knn[config, atom]),
                    "local_knn_percentile": float(support_percentile[config, atom]),
                    "nearest_corrected_config": int(reference_config_index[neighbours[0]]),
                    "nearest_corrected_atom": int(reference_atom_index[neighbours[0]]),
                    "force_error_norm_meV_A": float(atom_error[atom]),
                    "force_error_x_meV_A": float(errors[config, atom, 0] * 1000.0),
                    "force_error_y_meV_A": float(errors[config, atom, 1] * 1000.0),
                    "force_error_z_meV_A": float(errors[config, atom, 2] * 1000.0),
                    "nearest_distance_A": float(support_features[config][atom, 0]),
                    "second_distance_A": float(support_features[config][atom, 1]),
                    "third_distance_A": float(support_features[config][atom, 2]),
                }
            )

    projected_errors = np.asarray(projected_errors)
    remainder_errors = np.asarray(remainder_errors)
    aprime_errors = np.asarray(aprime_errors)
    aprime_radial_errors = np.asarray(aprime_radial_errors)
    aprime_remainder_errors = np.asarray(aprime_remainder_errors)
    atom_error_norm = np.linalg.norm(errors, axis=2) * 1000.0
    correlation = spearmanr(
        support_percentile.reshape(-1), atom_error_norm.reshape(-1)
    )

    selected_99 = [row for row in config_rows if row["sscha_index"] == 99]
    if len(selected_99) != 1:
        raise ValueError("expected exactly one sscha_index=99 record")
    config_99 = next(i for i, s in enumerate(support) if int(s.info["sscha_index"]) == 99)
    atom_99 = 48
    nearest_reference = support_knn_index[config_99, atom_99]
    atom_99_record = next(
        row
        for row in atom_rows
        if row["sscha_index"] == 99 and row["atom_index"] == atom_99
    )
    atom_99_record["five_nearest_corrected_environments"] = [
        {
            "config_index": int(reference_config_index[index]),
            "atom_index": int(reference_atom_index[index]),
            "standardized_distance": float(
                support_knn_distance.reshape(len(support), len(support[0]), 5)[
                    config_99, atom_99, rank
                ]
            ),
        }
        for rank, index in enumerate(nearest_reference)
    ]

    keep_without_99 = np.array(
        [int(s.info["sscha_index"]) != 99 for s in support], bool
    )
    geometry_local_in_domain = np.max(support_percentile, axis=1) < args.local_ood_percentile
    total_norm2 = float(np.sum(errors**2))
    radial_norm2 = float(np.sum(projected_errors**2))
    summary = {
        "status": "R2D_atom_local_support_and_radial_residual_diagnostic_complete",
        "interpretation_scope": (
            "geometry-only local support is fixed before reading DFT residual arrays; "
            "the nine structures remain development/training data, not a holdout"
        ),
        "fixed_condition": {
            "lattice_temperature_K": 450.0,
            "smearing": "fermi-dirac",
            "degauss_Ry": degauss,
        },
        "local_descriptor": {
            "features": "12 sorted neighbour distances plus 3 sorted first-shell bond-angle cosines",
            "scaling": "median and Gaussian-equivalent IQR on corrected-X0 atoms",
            "score": "mean standardized distance to 5 corrected-X0 atom environments",
            "reference_self_score": "same score excluding all atoms in the query configuration",
            "local_ood_percentile": args.local_ood_percentile,
            "n_reference_configurations": int(len(xats)),
            "n_reference_atomic_environments": int(len(reference_features)),
            "reference_knn_score_quantiles": quantiles(reference_knn),
        },
        "corrected_X0_configuration_minimum_bond_A": quantiles(reference_minimum_bond),
        "all_support": {
            "force_error": force_metrics(errors),
            "central_first_neighbour_radial_projection_force": force_metrics(projected_errors),
            "noncentral_remainder_force": force_metrics(remainder_errors),
            "force_squared_error_fraction_in_central_radial_subspace": (
                radial_norm2 / total_norm2 if total_norm2 > 0 else 0.0
            ),
            "Aprime_force_error": complex_metrics(aprime_errors),
            "Aprime_radial_projection": complex_metrics(aprime_radial_errors),
            "Aprime_noncentral_remainder": complex_metrics(aprime_remainder_errors),
            "atom_local_percentile_vs_force_error_norm_spearman": {
                "statistic": float(correlation.statistic),
                "pvalue": float(correlation.pvalue),
            },
        },
        "without_sscha99_geometry_only_diagnostic": {
            "n_structures": int(np.sum(keep_without_99)),
            "force_error": force_metrics(errors[keep_without_99]),
            "Aprime_force_error": complex_metrics(aprime_errors[keep_without_99]),
        },
        "local_in_domain_geometry_only_diagnostic": {
            "n_structures": int(np.sum(geometry_local_in_domain)),
            "sscha_indices": [
                int(s.info["sscha_index"])
                for s, keep in zip(support, geometry_local_in_domain, strict=True)
                if keep
            ],
            "force_error": (
                force_metrics(errors[geometry_local_in_domain])
                if np.any(geometry_local_in_domain)
                else None
            ),
            "Aprime_force_error": (
                complex_metrics(aprime_errors[geometry_local_in_domain])
                if np.any(geometry_local_in_domain)
                else None
            ),
        },
        "sscha99": {
            "configuration": selected_99[0],
            "atom48": atom_99_record,
        },
        "Aprime_mode": mode_provenance,
        "configuration_records": config_rows,
        "inputs": {
            "ensemble_xats": {"path": str(args.ensemble_xats), "sha256": sha256(args.ensemble_xats)},
            "support_data": {"path": str(args.support_data), "sha256": sha256(args.support_data)},
            "candidate_model": {"path": str(args.candidate_model), "sha256": sha256(args.candidate_model)},
            "operator": {"path": str(args.operator), "sha256": sha256(args.operator)},
            "background": {"path": str(args.background), "sha256": sha256(args.background)},
            "corrected_result": {"path": str(args.corrected_result), "sha256": sha256(args.corrected_result)},
        },
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    atomic_json(args.output_dir / "local_residual_diagnostic.json", summary)
    atomic_csv(
        args.output_dir / "configuration_records.csv",
        list(config_rows[0]),
        config_rows,
    )
    atomic_csv(
        args.output_dir / "atomic_environment_records.csv",
        [key for key in atom_rows[0] if key != "five_nearest_corrected_environments"],
        [
            {key: value for key, value in row.items() if key != "five_nearest_corrected_environments"}
            for row in atom_rows
        ],
    )
    atomic_npz(
        args.output_dir / "local_residual_arrays.npz",
        reference_minimum_bond_A=reference_minimum_bond,
        reference_knn_score=reference_knn,
        support_knn_score=support_knn,
        support_knn_percentile=support_percentile,
        force_error_eV_A=errors,
        central_radial_projection_eV_A=projected_errors,
        noncentral_remainder_eV_A=remainder_errors,
        Aprime_force_error_eV_A=aprime_errors,
        Aprime_radial_projection_eV_A=aprime_radial_errors,
        Aprime_noncentral_remainder_eV_A=aprime_remainder_errors,
    )

    figure, axes = plt.subplots(2, 2, figsize=(12.0, 8.3), constrained_layout=True)
    axes[0, 0].hist(reference_minimum_bond, bins=36, color="#9ecae1", edgecolor="white")
    axes[0, 0].set_xlabel("configuration minimum C-C distance (Å)")
    axes[0, 0].set_ylabel("corrected-X0 count")
    for row in config_rows:
        color = "#d62728" if row["sscha_index"] == 99 else "#444444"
        axes[0, 0].axvline(row["minimum_bond_A"], color=color, alpha=0.3, linewidth=1.0)
    axes[0, 0].axvline(
        selected_99[0]["minimum_bond_A"], color="#d62728", linewidth=2.0, label="sscha 99"
    )
    axes[0, 0].legend(loc="upper left", bbox_to_anchor=(1.01, 1.0), frameon=False)

    colors = plt.cm.tab10(np.linspace(0, 1, len(support)))
    for config, structure in enumerate(support):
        axes[0, 1].scatter(
            support_percentile[config],
            atom_error_norm[config],
            s=15,
            alpha=0.55,
            color=colors[config],
            label=str(int(structure.info["sscha_index"])),
        )
    axes[0, 1].scatter(
        [support_percentile[config_99, atom_99]],
        [atom_error_norm[config_99, atom_99]],
        marker="*",
        s=150,
        color="#d62728",
        edgecolor="black",
        linewidth=0.5,
        zorder=5,
        label="99 atom 48",
    )
    axes[0, 1].axvline(args.local_ood_percentile, color="black", linestyle="--", linewidth=1.0)
    axes[0, 1].set_xlabel("atom-local corrected-X0 kNN percentile")
    axes[0, 1].set_ylabel("force-error vector norm (meV/Å)")
    axes[0, 1].legend(
        title="sscha index",
        loc="upper left",
        bbox_to_anchor=(1.01, 1.0),
        ncol=1,
        frameon=False,
    )

    labels = [str(row["sscha_index"]) for row in config_rows]
    axes[1, 0].bar(
        np.arange(len(labels)),
        [row["radial_explained_fraction"] for row in config_rows],
        color=["#d62728" if label == "99" else "#4c78a8" for label in labels],
    )
    axes[1, 0].set_xticks(np.arange(len(labels)), labels)
    axes[1, 0].set_ylim(0, 1)
    axes[1, 0].set_xlabel("sscha index")
    axes[1, 0].set_ylabel("force-error fraction in central-bond subspace")

    x = np.arange(len(labels))
    width = 0.25
    axes[1, 1].bar(x - width, np.abs(aprime_errors) * 1000.0, width, label="total")
    axes[1, 1].bar(x, np.abs(aprime_radial_errors) * 1000.0, width, label="central radial")
    axes[1, 1].bar(x + width, np.abs(aprime_remainder_errors) * 1000.0, width, label="remainder")
    axes[1, 1].set_xticks(x, labels)
    axes[1, 1].set_xlabel("sscha index")
    axes[1, 1].set_ylabel("|A′ projected force error| (meV/Å)")
    axes[1, 1].legend(loc="upper left", bbox_to_anchor=(1.01, 1.0), frameon=False)

    figure.suptitle(
        "Graphene R2D local-support and conservative-radial residual diagnostic"
    )
    figure.savefig(args.output_dir / "local_residual_diagnostic.png", dpi=200)
    figure.savefig(args.output_dir / "local_residual_diagnostic.pdf")
    plt.close(figure)

    concise = {
        "all_support": summary["all_support"],
        "without_sscha99": summary["without_sscha99_geometry_only_diagnostic"],
        "local_in_domain": summary["local_in_domain_geometry_only_diagnostic"],
        "sscha99": summary["sscha99"],
    }
    print(json.dumps(concise, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
