#!/usr/bin/env python3
"""Post-hoc physical-symmetry audit of the frozen graphene q-space projector.

The final direct-DFPT holdout is not fitted or re-evaluated here.  This script
replays the already frozen baseline and blind scalar targets, extends the same
projector rule to symmetry-equivalent q points, and checks the invariants that
were not explicit in the original six holdout gates: Gamma acoustic modes,
Gamma-E2g degeneracy, time reversal, the sixfold stars near Gamma and at K,
and Hermiticity.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import graphene_p0_deploy as p0  # noqa: E402
from qspace_kohn_development import apply_top_projector  # noqa: E402
from qspace_kohn_model import build_primary_baseline  # noqa: E402


OUTDIR = ROOT / "results" / "p0_graphene_qspace"
DGS = (0.013, 0.027, 0.055)
THRESHOLDS = {
    "gamma_acoustic_max_abs_cm-1": 2.0,
    "gamma_e2g_splitting_cm-1": 0.05,
    "acoustic_change_after_correction_cm-1": 1.0e-5,
    "time_reversal_matrix_max_abs": 1.0e-10,
    "star_spectrum_spread_cm-1": 1.0e-5,
    "hermitian_matrix_max_abs": 1.0e-10,
}


def prediction_lookup() -> dict[tuple[float, str, float], float]:
    rows = {}
    path = OUTDIR / "holdout_blind_predictions.csv"
    with path.open(newline="") as handle:
        for raw in csv.DictReader(handle):
            key = (
                round(float(raw["degauss_Ry"]), 12),
                raw["region"],
                round(float(raw["t_GK"]), 12),
            )
            rows[key] = float(raw["predicted_f6_cm"])
    return rows


def qpoint_data(ph, fc: np.ndarray, qpoints: np.ndarray):
    ph.force_constants = fc
    ph.run_qpoints(qpoints, with_dynamical_matrices=True)
    result = ph.get_qpoints_dict()
    frequencies = np.sort(np.asarray(result["frequencies"], float), axis=1) * p0.CM
    matrices = np.asarray(result["dynamical_matrices"], complex)
    return frequencies, matrices


def matrix_frequencies_cm(
    matrix: np.ndarray, reference_matrix: np.ndarray, reference_cm: np.ndarray
) -> np.ndarray:
    herm = (matrix + matrix.conj().T) / 2
    eig = np.linalg.eigvalsh(herm)
    ref_eig = np.linalg.eigvalsh((reference_matrix + reference_matrix.conj().T) / 2)
    mask = (ref_eig > 1.0e-10) & (reference_cm > 1.0e-6)
    scale = float(np.median(reference_cm[mask] ** 2 / ref_eig[mask]))
    return np.sign(eig) * np.sqrt(np.abs(eig) * scale)


def corrected_matrix(
    matrix: np.ndarray,
    base_frequency_cm: np.ndarray,
    target_top_cm: float,
    gamma_degenerate: bool,
) -> tuple[np.ndarray, np.ndarray]:
    delta_lambda = target_top_cm**2 - float(base_frequency_cm[-1]) ** 2
    corrected = apply_top_projector(
        matrix,
        delta_lambda,
        base_frequency_cm,
        gamma_degenerate=gamma_degenerate,
    )
    frequencies = matrix_frequencies_cm(corrected, matrix, base_frequency_cm)
    return corrected, frequencies


def sixfold_star(scale: float) -> np.ndarray:
    # Reduced reciprocal coordinates generated by successive C6 rotations of
    # (scale, scale).  scale=1/3 gives the K/K' star; scale=0.015 gives the
    # sixfold star at the frozen Gamma-ray t=0.045 point.
    return np.asarray(
        [
            [scale, scale, 0.0],
            [-scale, 2 * scale, 0.0],
            [-2 * scale, scale, 0.0],
            [-scale, -scale, 0.0],
            [scale, -2 * scale, 0.0],
            [2 * scale, -scale, 0.0],
        ],
        float,
    )


def main() -> int:
    manifest = json.loads((OUTDIR / "freeze_manifest.json").read_text())
    if manifest["status"] != "frozen_before_holdout":
        raise RuntimeError("unexpected frozen-model manifest status")
    predictions = prediction_lookup()
    model = build_primary_baseline()
    records = []

    for dg in DGS:
        cache = OUTDIR / "baseline_cache" / (
            f"graphene_8x8_dg{p0.dg_slug(dg)}_baseline_fc2.npz"
        )
        with np.load(cache, allow_pickle=False) as data:
            fc = np.asarray(data["fc2"], float)

        gamma_star = sixfold_star(0.015)  # t=0.045 on the archived Gamma ray
        k_star = sixfold_star(1.0 / 3.0)
        all_q = np.vstack([np.zeros((1, 3)), gamma_star, k_star])
        base_freq, base_matrix = qpoint_data(model.ph, fc, all_q)

        target_gamma0 = predictions[(round(dg, 12), "G", 0.0)]
        target_gamma_ray = predictions[(round(dg, 12), "G", 0.045)]
        target_k = predictions[(round(dg, 12), "K", 1.0)]

        corrected = []
        corrected_freq = []
        for index, target, degenerate in [
            (0, target_gamma0, True),
            *[(index, target_gamma_ray, True) for index in range(1, 7)],
            *[(index, target_k, False) for index in range(7, 13)],
        ]:
            matrix, frequencies = corrected_matrix(
                base_matrix[index], base_freq[index], target, degenerate
            )
            corrected.append(matrix)
            corrected_freq.append(frequencies)
        corrected = np.asarray(corrected)
        corrected_freq = np.asarray(corrected_freq)

        gamma0_base = base_freq[0]
        gamma0_corrected = corrected_freq[0]
        gamma_star_freq = corrected_freq[1:7]
        k_star_freq = corrected_freq[7:13]

        # Opposite members are indices 0 and 3 of each sixfold star.
        time_reversal_gamma = float(
            np.max(np.abs(corrected[1] - corrected[4].conj()))
        )
        time_reversal_k = float(
            np.max(np.abs(corrected[7] - corrected[10].conj()))
        )
        hermitian_error = float(
            np.max(np.abs(corrected - corrected.conj().transpose(0, 2, 1)))
        )

        record = {
            "degauss_Ry": dg,
            "gamma_acoustic_base_max_abs_cm-1": float(
                np.max(np.abs(gamma0_base[:3]))
            ),
            "gamma_acoustic_corrected_max_abs_cm-1": float(
                np.max(np.abs(gamma0_corrected[:3]))
            ),
            "gamma_acoustic_change_max_abs_cm-1": float(
                np.max(np.abs(gamma0_corrected[:3] - gamma0_base[:3]))
            ),
            "gamma_e2g_base_splitting_cm-1": float(
                abs(gamma0_base[-1] - gamma0_base[-2])
            ),
            "gamma_e2g_corrected_splitting_cm-1": float(
                abs(gamma0_corrected[-1] - gamma0_corrected[-2])
            ),
            "time_reversal_gamma_matrix_max_abs": time_reversal_gamma,
            "time_reversal_K_matrix_max_abs": time_reversal_k,
            "gamma_star_all_branch_spread_cm-1": float(
                np.max(np.ptp(gamma_star_freq, axis=0))
            ),
            "K_star_all_branch_spread_cm-1": float(
                np.max(np.ptp(k_star_freq, axis=0))
            ),
            "corrected_hermitian_max_abs": hermitian_error,
        }
        records.append(record)

    maxima = {
        "gamma_acoustic_max_abs_cm-1": max(
            row["gamma_acoustic_corrected_max_abs_cm-1"] for row in records
        ),
        "gamma_e2g_splitting_cm-1": max(
            row["gamma_e2g_corrected_splitting_cm-1"] for row in records
        ),
        "acoustic_change_after_correction_cm-1": max(
            row["gamma_acoustic_change_max_abs_cm-1"] for row in records
        ),
        "time_reversal_matrix_max_abs": max(
            max(
                row["time_reversal_gamma_matrix_max_abs"],
                row["time_reversal_K_matrix_max_abs"],
            )
            for row in records
        ),
        "star_spectrum_spread_cm-1": max(
            max(
                row["gamma_star_all_branch_spread_cm-1"],
                row["K_star_all_branch_spread_cm-1"],
            )
            for row in records
        ),
        "hermitian_matrix_max_abs": max(
            row["corrected_hermitian_max_abs"] for row in records
        ),
    }
    gates = {
        name: {
            "observed": value,
            "threshold": THRESHOLDS[name],
            "pass": value < THRESHOLDS[name],
        }
        for name, value in maxima.items()
    }
    summary = {
        "status": "PASS" if all(gate["pass"] for gate in gates.values()) else "FAIL",
        "scope": (
            "post-hoc invariant audit of the frozen baseline/projector; no "
            "direct-DFPT holdout target was fitted or changed"
        ),
        "degauss_Ry": list(DGS),
        "gates": gates,
        "records": records,
    }
    OUTDIR.mkdir(parents=True, exist_ok=True)
    with (OUTDIR / "qspace_symmetry_audit.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(records[0]))
        writer.writeheader()
        writer.writerows(records)
    (OUTDIR / "qspace_symmetry_audit.json").write_text(
        json.dumps(summary, indent=2) + "\n"
    )
    print(json.dumps(summary, indent=2))
    return 0 if summary["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
